### ISSUE TITLE
Getting Invalid config file Error

### ISSUE THREAD

**Issue by Shawful** [dtabuenc/karma-html-reporter#17]
Hello, I just wanted to let you know that with this reporter, I am getting the following error:

ERROR [config]: Invalid config file!
 SyntaxError:  Unexpected identifier.

My command prompt tells me that the error is on the following line of code:

reporters: ['progress', 'html'],

However, I'm following the instructions outlined on both the npm page and the github account.

Any ideas on what I might be doing wrong?

NPM Project
https://www.npmjs.com/package/karma-html-reporter

**Comment by Shawful** [comment]
I resolved the above error by moving the reporters line of code to exist immediately after my config.set({ line of code.

However, now I receive a different error:

ERROR [karma]: [TypeError: Cannot call method 'push' of undefined]

Ideas?

**Comment by dtabuenc** [comment]
Without more information about the config, there's not a lot I can tell from those error messages, although they don't really seem to be specific to the html-reporter.

**Comment by Shawful** [comment]
I resolved that error by reviewing my installations.  Some plugins were global, otheres were local, but eventually I found a combination that worked.
