### ISSUE TITLE
 Cannot write HTML report ENOENT, open ''

### ISSUE THREAD

**Issue by sagarrayudu** [dtabuenc/karma-html-reporter#28]
Cannot write HTML report ENOENT

**Comment by M0nter0** [comment]
I was having the same issue. Check you don't have the [karma-htmlfile-reporter](https://www.npmjs.com/package/karma-htmlfile-reporter) plugin installed. Both are using 'html' as key name for reporters. 
When I uninstalled it, karma-html-reporter started working fine.
